---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

```{r library, echo = FALSE}
library(icecovid19)
library(tibble)
library(DT)
```

# icecovid19

<!-- badges: start -->
<!-- badges: end -->

The goal of the package is to deploy a shiny app and the data and functions required for the app to run. 

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("etc5523-2020/r-package-assessment-Thanh-8213")
```
## Examples

### Dataset example: Data_total
```{r data, warning = FALSE}
as_tibble(data_total)
```

### Function example
Here are some example of the functions in this package:

#### summariseData function
```{r function1, warning = FALSE}
as_tibble(summariseData(data_total, date))
```

#### getSummaryDT function


```{r function2, warning = FALSE}
getSummaryDT(data_total, `Country/Region`)
```

