---
title: "Tracking the evolution of the pandemic"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tracking the evolution of the pandemic}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## App Introduction 

### What the shiny app does
This dashboard shows the status of the COVID19 virus across the world. It gives the user the opportunity to view the spreading of the Great Pandemic. The map provides worldwide view of the disease while detailed information of each country is demonstrated by the data table. 
The app also illustrates the evolution of the virus by two plots in plots tab.

### Instruction on launching the app
First, you need to install the package using 
``` r
# install.packages("devtools")
devtools::install_github("etc5523-2020/r-package-assessment-Thanh-8213")
```
Then, you can use the function `launch_app()` to launch the shiny app. This can be done by typing `launch_app()` in the console.

### Instruction on how using the app 

1. The first tab you will see is the overview tab. It contains a slider, a bubble map and a summary datatable. 
The slider control the date at which the data is recorded. You can change it to understand how the virus spread overtime. The map will provide the name of the country, the number of confirmed cases, number of deaths and number of recovered cases when you hover your mouse on the bubble. 
The datatable gives detailed number of number of confirmed cases, number of deaths and number of recovered cases, in case you can not find the data you needed on the map. 

2. The second tab you will see is the Plots tab. It contains two plots and one box.
The first plot is "Overall trend of COVID19". You can hover your mouse on the graph to get further information.  
The second plot is "Evolution of COVID19 per criteria". Together with it comes a select box. You can explore detailed information about a certain type of cases by selecting in this box. You can hover your mouse on the graph to get detailed information. 
You can click the first plot for a little surprise ;)
3. The third tab is About tab. 
It contains information of the author and the purpose of the app. Nothing special there ;)

